name: e2e-tests
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'test command'
        required: true
        type: string
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npx cypress run
