name: Manual Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cypressCommand:
        description: 'Cypress Command'
        required: true
        default: 'npx cypress run' # Здесь указывается команда для запуска тестов

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        start: ${{ inputs.cypressCommand }}
